name: quiz
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  circular_countdown_timer: ^0.2.3
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets: 
    - assets/images/
    - assets/images/scifi/
    - assets/images/fantasia/
    - assets/images/terror/
  uses-material-design: true
